"""
FastAPI server — entrypoint for the AI girlfriend chat demo.
Replaces the Telegram bot with HTTP + WebSocket endpoints.
"""

import asyncio
import json
import logging
import random
import re
import time
from contextlib import asynccontextmanager
from typing import Any

from fastapi import FastAPI, HTTPException, Response, WebSocket, WebSocketDisconnect, Query
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field

from bot.config import (
    SERVER_HOST, SERVER_PORT, DEFAULT_USER_ID, PERSONA_FILE_SEXTING,
    GEMINI_FALLBACK_MODEL, DEMO_WALLET_REFILL_TOKENS,
    COMMERCE_DEV_RESET_ENABLED,
)
from bot.memory.db import init_db, get_connection
from bot.memory.stm import get_all_messages
from bot.persona import load_persona
from bot.providers.gemini_provider import GeminiProvider
from bot.providers.grok_provider import GrokProvider
from bot.chat_engine import ChatEngine, ChatResponse
from bot.moderation import ModerationProviderChain
from bot.text_style import capitalize_names, capitalize_user_name
from bot.media_delivery import (
    MediaDeliveryError,
    R2DeliveryConfig,
    create_signed_get_url,
    full_media_ttl,
    preview_media_ttl,
    r2_is_configured,
    r2_object_exists,
    validate_media_delivery_config,
)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger(__name__)

MAX_USER_MESSAGE_CHARS = 6000
MAX_USER_NAME_CHARS = 48

# Global chat engine
engine: ChatEngine | None = None
moderation_provider = None
commerce_service: Any | None = None
media_catalog: Any | None = None
commerce_delivery_ready = False


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Initialize DB and providers on startup."""
    global engine, moderation_provider, commerce_service, media_catalog
    global commerce_delivery_ready

    logger.info("Initializing database...")
    await init_db()

    logger.info("Loading persona...")
    persona = load_persona(PERSONA_FILE_SEXTING)
    nsfw_persona = persona  # one always-open persona drives everything
    logger.info("Persona loaded: %s", persona.name)

    # Load and statically validate the authored media catalog on every start.
    # Full object delivery is enabled only when a complete private-R2
    # configuration is present. This keeps ordinary chat available in local
    # environments that have not provisioned their demo media bucket yet.
    from bot.media_commerce import get_media_commerce_service

    commerce_service = get_media_commerce_service()
    media_catalog = commerce_service.catalog
    r2_configured = r2_is_configured()
    commerce_delivery_ready = r2_configured and bool(media_catalog.items)
    if commerce_delivery_ready:
        from bot.media_catalog import validate_catalog_objects

        validate_media_delivery_config()
        logger.info("Validating private R2 media catalog objects...")
        await validate_catalog_objects(media_catalog, r2_object_exists)
        logger.info("Private media delivery ready (%d catalog items)", len(media_catalog.items))
    elif not r2_configured:
        logger.warning(
            "Cloudflare R2 is not configured; wallet/gallery APIs remain available "
            "but chat media offers and unlocks are disabled"
        )
    else:
        logger.warning(
            "The private media catalog is empty; wallet/gallery APIs remain available "
            "but chat media offers and unlocks are disabled"
        )

    logger.info("Initializing LLM providers...")
    # Mia is always-open, so every reply is generated by Grok (nsfw_provider).
    nsfw_provider = GrokProvider()
    classifier_provider = GeminiProvider()
    # thinking_budget=0 → no "thinking" latency; this provider only writes short
    # replies (suggestions + Grok fallback), so speed matters more than reasoning.
    fallback_provider = GeminiProvider(GEMINI_FALLBACK_MODEL, thinking_budget=0)
    # Use the available Gemini path first, then Grok when Gemini returns an
    # invalid/safety-filtered result. Only a failure of both providers blocks
    # fail-closed, so one exhausted API account cannot reject harmless chat.
    moderation_provider = ModerationProviderChain(fallback_provider, nsfw_provider)

    engine = ChatEngine(
        persona=persona,
        nsfw_persona=nsfw_persona,
        nsfw_provider=nsfw_provider,
        classifier_provider=classifier_provider,
        fallback_provider=fallback_provider,
        moderation_provider=moderation_provider,
        commerce_service=commerce_service if commerce_delivery_ready else None,
    )
    logger.info("Chat engine ready")

    yield

    logger.info("Shutting down")


app = FastAPI(title="AI Girlfriend Chat", lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ------------------------------------------------------------------
# REST endpoints
# ------------------------------------------------------------------

# NOTE: The sidebar profile (name, tagline, bio, "about me" grid) is curated
# directly in the frontend (frontend/app/page.tsx -> PROFILE). There is no
# /api/profile endpoint: the persona YAML doesn't carry that presentational copy,
# so the frontend is the single source of truth for profile display.


class IdempotencyRequest(BaseModel):
    idempotency_key: str = Field(
        min_length=8,
        max_length=128,
        pattern=r"^[A-Za-z0-9][A-Za-z0-9:_.-]*$",
    )


def _commerce_value(value: object, key: str, default: object = None) -> object:
    if isinstance(value, dict):
        return value.get(key, default)
    try:
        return value[key]  # type: ignore[index]
    except (KeyError, TypeError, IndexError):
        return getattr(value, key, default)


def _commerce_user_id(user_id: int | None) -> int:
    uid = DEFAULT_USER_ID if user_id is None else user_id
    if uid <= 0:
        raise HTTPException(status_code=422, detail="user_id must be positive")
    return uid


def _private_no_store(response: Response) -> None:
    response.headers["Cache-Control"] = "private, no-store"


def _require_commerce_service() -> Any:
    if commerce_service is None or media_catalog is None:
        raise HTTPException(status_code=503, detail="Commerce service is not ready")
    return commerce_service


def _require_media_delivery() -> None:
    if not commerce_delivery_ready:
        raise HTTPException(
            status_code=503,
            detail="Private media delivery is not configured",
        )
    # Re-validate the in-memory configuration before any operation that could
    # debit tokens. It is intentionally done before unlock, never after.
    try:
        R2DeliveryConfig.from_environment()
    except MediaDeliveryError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc


def _catalog_item(content_id: str) -> Any:
    _require_commerce_service()
    item = media_catalog.get(content_id)
    if item is None:
        raise HTTPException(status_code=404, detail="Media item is unavailable")
    return item


def _signed_derivative_url(object_key: str | None) -> str:
    if not object_key or not commerce_delivery_ready:
        return ""
    try:
        url, _ = create_signed_get_url(
            object_key,
            expires_seconds=preview_media_ttl(),
        )
        return url
    except MediaDeliveryError:
        logger.exception("Could not sign private media derivative")
        return ""


async def _is_entitled(user_id: int, content_id: str) -> bool:
    service = _require_commerce_service()
    check = getattr(service, "has_entitlement", None)
    if not callable(check):
        raise HTTPException(status_code=503, detail="Entitlement service is unavailable")
    return bool(await check(user_id, content_id))


async def _media_offer_payload(user_id: int, offer: object) -> dict:
    offer_id = _commerce_value(offer, "offer_id", _commerce_value(offer, "id"))
    content_id = str(_commerce_value(offer, "content_id", ""))
    if offer_id is None or not content_id:
        raise ValueError("Incomplete media offer")
    item = _catalog_item(content_id)
    price = _commerce_value(offer, "price_tokens")
    if price is None:
        raise ValueError("Media offer has no price snapshot")

    unlocked_hint = _commerce_value(offer, "unlocked", None)
    unlocked = (
        bool(unlocked_hint)
        if unlocked_hint is not None
        else await _is_entitled(user_id, item.id)
    )
    return {
        "offer_id": str(offer_id),
        "content_id": item.id,
        "media_type": item.media_type,
        "price_tokens": int(price),
        "preview_url": _signed_derivative_url(item.preview_key),
        "poster_url": (
            _signed_derivative_url(item.poster_key) if item.poster_key else None
        ),
        "aspect_ratio": float(item.aspect_ratio),
        "duration_seconds": item.duration_seconds,
        "unlocked": unlocked,
    }


async def _gallery_item_payload(user_id: int, entitlement: object) -> dict:
    content_id = str(_commerce_value(entitlement, "content_id", ""))
    item = _catalog_item(content_id)
    # list_gallery is entitlement-derived, but retain a defence-in-depth check
    # before returning even a preview for a purported gallery row.
    if not await _is_entitled(user_id, content_id):
        raise HTTPException(status_code=403, detail="Media item is locked")
    return {
        "content_id": content_id,
        "media_type": item.media_type,
        "aspect_ratio": float(item.aspect_ratio),
        "duration_seconds": item.duration_seconds,
        "unlocked_at": float(_commerce_value(entitlement, "unlocked_at", 0)),
        "preview_url": _signed_derivative_url(item.preview_key),
        "poster_url": (
            _signed_derivative_url(item.poster_key) if item.poster_key else None
        ),
    }


def _wallet_balance(result: object) -> int:
    value = _commerce_value(result, "balance", result)
    try:
        return int(value)
    except (TypeError, ValueError) as exc:
        raise RuntimeError("Commerce service returned an invalid balance") from exc


def _commerce_http_error(exc: Exception) -> HTTPException:
    code = str(getattr(exc, "code", "") or exc.__class__.__name__).lower()
    message = str(exc).strip() or "Commerce operation failed"
    if "insufficient" in code:
        return HTTPException(status_code=402, detail=message)
    if "not_found" in code or "notfound" in code or "unavailable" in code:
        return HTTPException(status_code=404, detail=message)
    if "forbidden" in code or "locked" in code or "owner" in code:
        return HTTPException(status_code=403, detail=message)
    if "conflict" in code or "idempot" in code:
        return HTTPException(status_code=409, detail=message)
    if "invalid" in code:
        return HTTPException(status_code=400, detail=message)
    logger.exception("Unexpected commerce service error", exc_info=exc)
    return HTTPException(status_code=500, detail="Commerce operation failed")


# Inspiration angles for the LLM-generated opening — one is sampled per
# generation so first messages land on a different excuse every time.
# They are hints, not scripts: the instruction tells her to invent her own.
# ALL of them are rooted in the night they met at a club party (see her
# core memories): this is her FIRST text to him ever, so the
# hook must be the one thing THEY share — that night — not her opaque
# daily life.
_OPENING_ANGLES_CLUB = [
    "you finally caved and texted — that eye contact when you met at the club hasn't left your head",
    "you got his number off Tyler's phone at the club and he doesn't know that yet",
    "you almost texted him every day since the club and today you stopped chickening out",
    "you bring up the moment at the club when you caught him staring at you across the dance floor",
    "a song from that night at the club just came on and now texting him is his problem",
    "you tease that Tyler keeps bringing him up and now that night at the club is stuck in your head again",
    "you still remember exactly what he was wearing at the club and you're not over it",
    "you tell him you knew you'd end up texting him the second you two locked eyes at the club",
]


async def _generate_dynamic_opening(engine: ChatEngine) -> str:
    """Ask the LLM to write Mia's opening message — fresh every time.

    Includes the same time-of-day / location context that build_prompt injects
    into every reply, so the opening is consistent with where she'll say she is
    once he answers. Without it the bare persona defaults to a generic vibe
    that then contradicts the first time-aware reply.
    """
    from bot.time_context import get_time_prompt
    # Locked register: the conversation hasn't started, so the opening must be
    # a teasing hook, not explicit — HE is the one who unlocks that register.
    persona_prompt = engine.persona.to_system_prompt(include_unlocked=False)
    time_prompt = await get_time_prompt(heat="low")
    # One randomly-picked angle as INSPIRATION (never a script). Every angle
    # circles the club night where they met — the shared memory that makes a
    # first text from her instantly make sense to him.
    angle = random.choice(_OPENING_ANGLES_CLUB)
    messages = [
        {
            "role": "system",
            "content": (
                f"{persona_prompt}\n\n"
                f"{time_prompt}\n\n"
                "You are texting him FIRST — your first text to him EVER. The reason "
                "you're texting is the night you two MET: the party at "
                "the club Tyler dragged everyone to (see your core memories — the "
                "bikini top, the eye contact across the dance floor, the number you "
                "took off Tyler's phone). Reference that night so he instantly knows "
                "who you are and why you're in his phone. Where you are right now "
                "(above) can color the text, but that club night is the hook. "
                f"For inspiration only (do NOT copy it, invent your own if better): {angle}. "
                "STRUCTURE: 2-3 short texts, each on its own line. The FIRST text is "
                "ALWAYS just a short greeting — like 'hey', 'heyy', 'hey you', 'hey, "
                "how are you' — in your own words, vary it every time. THEN the next "
                "text(s) carry the reason you're texting. Each text is SHORT — 5-12 "
                "words, the way a real girl actually types — never a chain of clauses. "
                "No period at the end. Lowercase is your style EXCEPT people's names — "
                "those are ALWAYS capitalized: Tyler, never 'tyler'. "
                "TONE: casual and warm with a teasing edge — you finally texted the guy "
                "you've been thinking about since the party, but you keep it playful, "
                "not desperate. At most a light flirty undertone; ZERO thirst. "
                "NOT explicit — no 'wet', no anatomy, no graphic desires; you "
                "never cross that line first. Do NOT mention your friends "
                "by name (Jess, Cara, Lena) in this opening — he doesn't know them yet; "
                "Tyler is fine to mention. Do NOT reuse the phrasing of your "
                "opening_lines — say something fresh, in your own words."
            ),
        },
        {"role": "user", "content": "(he hasn't said anything yet — you're texting first)"},
    ]
    # Use the shared primary -> fallback path so both candidates cross the
    # deterministic output guard and the full async moderation gate. Returning
    # empty makes the caller choose the authored static opening.
    opening = await engine._generate_with_fallback(
        engine.nsfw_provider,
        messages,
        heat="low",
    )
    if not opening:
        raise RuntimeError("Dynamic opening rejected by output validation")
    return opening


@app.get("/api/history/{mode}")
async def get_history(
    mode: str,
    response: Response,
    user_id: int = Query(default=None),
):
    """Return chat history for a specific mode. Opening message is sent via WebSocket."""
    user_id = _commerce_user_id(user_id)
    _private_no_store(response)
    if mode != "sexting":
        return JSONResponse({"error": "Invalid mode"}, status_code=400)

    messages = await get_all_messages(user_id, mode=mode)

    out = []
    for m in messages:
        if m["role"] not in ("user", "assistant"):
            continue
        entry = {
            "type": "text",
            "id": f"text-{m['id']}",
            "role": m["role"],
            "content": m["content"],
            "timestamp": m["timestamp"],
            "mode": mode,
        }
        out.append(entry)

    service = _require_commerce_service()
    try:
        offers = await service.list_delivered_offers(user_id)
        for offer in offers:
            offered_at = float(_commerce_value(offer, "offered_at", 0) or 0)
            try:
                payload = await _media_offer_payload(user_id, offer)
            except (HTTPException, KeyError, TypeError, ValueError):
                logger.exception("Skipping invalid persisted media offer in history")
                continue
            out.append(
                {
                    "type": "media_offer",
                    "id": f"media-offer-{payload['offer_id']}",
                    "role": "assistant",
                    "timestamp": offered_at,
                    "mode": mode,
                    "offer": payload,
                }
            )
    except Exception as exc:
        # History text remains usable if commerce storage is temporarily down.
        logger.warning("Could not load media offers for user %d: %s", user_id, exc)

    out.sort(
        key=lambda item: (
            float(item.get("timestamp", 0)),
            1 if item.get("type") == "media_offer" else 0,
            str(item.get("id", "")),
        )
    )

    return {"mode": mode, "messages": out}


@app.get("/api/demo/wallet")
async def get_demo_wallet(
    response: Response,
    user_id: int = Query(default=None),
):
    uid = _commerce_user_id(user_id)
    _private_no_store(response)
    service = _require_commerce_service()
    try:
        wallet = await service.get_wallet(uid)
    except Exception as exc:
        raise _commerce_http_error(exc) from exc
    return {"balance": _wallet_balance(wallet)}


@app.post("/api/demo/wallet/refill")
async def refill_demo_wallet(
    request: IdempotencyRequest,
    user_id: int = Query(default=None),
):
    uid = _commerce_user_id(user_id)
    service = _require_commerce_service()
    try:
        result = await service.refill_wallet(uid, request.idempotency_key)
    except Exception as exc:
        raise _commerce_http_error(exc) from exc
    credited = _commerce_value(
        result,
        "credited",
        _commerce_value(result, "amount_tokens", DEMO_WALLET_REFILL_TOKENS),
    )
    return {"balance": _wallet_balance(result), "credited": int(credited)}


@app.post("/api/media/offers/{offer_id}/unlock")
async def unlock_media_offer(
    offer_id: str,
    request: IdempotencyRequest,
    user_id: int = Query(default=None),
):
    uid = _commerce_user_id(user_id)
    if not offer_id.isdigit() or len(offer_id) > 20 or int(offer_id) <= 0:
        raise HTTPException(status_code=404, detail="Media offer was not found")
    _require_media_delivery()
    service = _require_commerce_service()
    try:
        result = await service.unlock_offer(uid, offer_id, request.idempotency_key)
    except Exception as exc:
        raise _commerce_http_error(exc) from exc

    entitlement = _commerce_value(result, "entitlement")
    content_id = str(
        _commerce_value(
            entitlement,
            "content_id",
            _commerce_value(result, "content_id", ""),
        )
    )
    if not content_id:
        raise HTTPException(status_code=500, detail="Invalid entitlement response")
    item = _catalog_item(content_id)
    balance = _wallet_balance(result)
    already_unlocked = bool(_commerce_value(result, "already_unlocked", False))

    try:
        await manager.send_json(
            uid,
            {
                "type": "media_entitlement_updated",
                "offer_id": offer_id,
                "content_id": content_id,
                "balance": balance,
            },
        )
    except Exception:
        # The atomic debit/entitlement transaction is already committed. A
        # socket that disappeared between click and response must not turn a
        # successful purchase into a 500; reconnect/history will restore it.
        logger.warning("Entitlement committed but WebSocket notify failed for user %d", uid)
    return {
        "balance": balance,
        "already_unlocked": already_unlocked,
        "entitlement": {
            "content_id": content_id,
            "media_type": item.media_type,
        },
    }


@app.get("/api/media/gallery")
async def get_media_gallery(
    response: Response,
    user_id: int = Query(default=None),
):
    uid = _commerce_user_id(user_id)
    _private_no_store(response)
    service = _require_commerce_service()
    try:
        rows = await service.list_gallery(uid)
    except Exception as exc:
        raise _commerce_http_error(exc) from exc

    items = []
    for row in rows:
        try:
            items.append(await _gallery_item_payload(uid, row))
        except HTTPException as exc:
            if exc.status_code in {403, 404}:
                logger.warning("Skipping stale gallery entitlement for user %d", uid)
                continue
            raise
    return {"items": items}


@app.get("/api/media/{content_id}/access")
async def get_media_access(
    content_id: str,
    response: Response,
    user_id: int = Query(default=None),
):
    uid = _commerce_user_id(user_id)
    _private_no_store(response)
    _require_media_delivery()
    service = _require_commerce_service()
    item = _catalog_item(content_id)
    if not await _is_entitled(uid, content_id):
        raise HTTPException(status_code=403, detail="Media item is locked")

    try:
        access_url, expires_at = create_signed_get_url(
            item.full_key,
            expires_seconds=full_media_ttl(item.media_type),
        )
    except MediaDeliveryError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc

    try:
        await service.mark_media_opened(uid, content_id)
    except Exception:
        # first_opened_at is analytics only; an existing entitlement remains
        # authoritative if that write is temporarily unavailable.
        logger.warning("Could not mark media %s opened for user %d", content_id, uid)
    return {
        "content_id": content_id,
        "media_type": item.media_type,
        "access_url": access_url,
        "mime_type": item.mime_type,
        "expires_at": expires_at,
    }


@app.post("/api/dev/commerce/reset")
async def reset_demo_commerce(user_id: int = Query(default=None)):
    if not COMMERCE_DEV_RESET_ENABLED:
        # Hide a destructive development helper entirely in normal deployments.
        raise HTTPException(status_code=404, detail="Not found")
    uid = _commerce_user_id(user_id)
    service = _require_commerce_service()
    try:
        await service.reset_user_commerce(uid)
    except Exception as exc:
        raise _commerce_http_error(exc) from exc
    return {"status": "ok", "user_id": uid}


@app.post("/api/suggest")
async def suggest_reply(user_id: int = Query(default=None), mode: str = Query(default="sexting")):
    """AI Help — generate a suggested reply for the user to send to Mia."""
    if not engine:
        return JSONResponse({"error": "Engine not ready"}, status_code=503)
    if mode != "sexting":
        return JSONResponse({"error": "Invalid mode"}, status_code=400)
    uid = user_id or DEFAULT_USER_ID
    try:
        suggestion = await engine.suggest_reply(uid, mode=mode)
    except Exception as e:
        logger.warning("Suggest endpoint failed: %s", e)
        suggestion = ""
    return {"suggestion": suggestion}


@app.post("/api/reset")
async def reset_user(user_id: int = Query(default=None)):
    """Reset chat data while preserving wallet, offers and entitlements."""
    uid = user_id or DEFAULT_USER_ID
    conn = await get_connection()
    try:
        for table in ("messages", "memories", "user_facts", "sent_content",
                      "shared_content"):
            try:
                await conn.execute(f"DELETE FROM {table} WHERE user_id = ?", (uid,))
            except Exception:
                logger.debug("Reset skipped table %s (may not exist yet)", table, exc_info=True)
        # Commerce pacing uses total_messages as its monotonic processed-batch
        # number. Preserve that counter and every sales_* field so reset cannot
        # bypass a cooldown or rewind offer rotation. Only transient presence
        # data is cleared for the fresh conversation.
        await conn.execute(
            """
            UPDATE engagement_state
            SET nsfw_count = 0,
                last_push_at = 0,
                last_message_at = 0,
                last_reengage_at = 0,
                first_message_at = NULL,
                last_push_content_id = NULL
            WHERE user_id = ?
            """,
            (uid,),
        )
        await conn.commit()
        logger.info("Reset chat data for user %d (commerce preserved)", uid)
    finally:
        await conn.close()

    # Clear in-memory per-user state too — otherwise a stuck/old batch task, a
    # held processing lock, or stale counters survive the reset and can block
    # the fresh conversation (the "no reply after reset" bug).
    _cancel_idle(uid)
    nudge_counts.pop(uid, None)
    _openings_started.discard(uid)
    if engine:
        engine.clear_user_state(uid)
    from bot.memory.ltm import clear_retrieval_state
    clear_retrieval_state(uid)
    from bot.mood import clear_mood_state
    clear_mood_state(uid)

    return {"status": "ok", "user_id": uid}


# ------------------------------------------------------------------
# WebSocket chat
# ------------------------------------------------------------------

class ConnectionManager:
    """Track active WebSocket connections."""

    def __init__(self):
        self.active: dict[int, WebSocket] = {}

    async def connect(self, user_id: int, ws: WebSocket):
        await ws.accept()
        previous = self.active.get(user_id)
        self.active[user_id] = ws
        # One browser reconnect can overlap the old socket's close event. Keep
        # the newest socket authoritative and retire the superseded one; its
        # eventual ``finally`` must not be allowed to remove this replacement.
        if previous is not None and previous is not ws:
            try:
                await previous.close(code=1000, reason="Replaced by a newer connection")
            except Exception:
                logger.debug(
                    "Could not close superseded WebSocket for user %d",
                    user_id,
                    exc_info=True,
                )
        logger.info("WebSocket connected: user %d", user_id)

    def disconnect(self, user_id: int, ws: WebSocket | None = None):
        # A stale socket can finish closing after a reconnect has already put a
        # newer socket in the map. Only its own connection may remove itself.
        if ws is not None and self.active.get(user_id) is not ws:
            logger.debug("Ignoring stale WebSocket disconnect for user %d", user_id)
            return
        self.active.pop(user_id, None)
        logger.info("WebSocket disconnected: user %d", user_id)

    async def send_json(self, user_id: int, data: dict):
        ws = self.active.get(user_id)
        if ws:
            await ws.send_json(data)


manager = ConnectionManager()


# ------------------------------------------------------------------
# Online-only re-engagement ("double-text" when the user goes quiet
# while still connected). No offline queue, no cron for absent users.
# ------------------------------------------------------------------

IDLE_NUDGE_MIN_SECONDS = 120   # wait 2–4 min before a spontaneous follow-up
IDLE_NUDGE_MAX_SECONDS = 240
MAX_CONSECUTIVE_NUDGES = 1      # at most one nudge, then stay quiet until he writes

idle_tasks: dict[int, asyncio.Task] = {}
nudge_counts: dict[int, int] = {}
# Users whose one-time opening has already been started this process. Guards
# against concurrent reconnects (reload / StrictMode double-mount) regenerating
# the opening before the first assistant row is persisted.
_openings_started: set[int] = set()


def _cancel_idle(user_id: int):
    """Cancel any pending idle-nudge task for a user."""
    task = idle_tasks.pop(user_id, None)
    if task and not task.done():
        task.cancel()


def _schedule_idle_nudge(user_id: int):
    """(Re)start the idle-nudge countdown for a user."""
    _cancel_idle(user_id)
    idle_tasks[user_id] = asyncio.create_task(_idle_nudge_worker(user_id))


async def _idle_nudge_worker(user_id: int):
    """After a quiet gap (still online), send a spontaneous follow-up."""
    import random
    try:
        await asyncio.sleep(random.uniform(IDLE_NUDGE_MIN_SECONDS, IDLE_NUDGE_MAX_SECONDS))

        if user_id not in manager.active or not engine:
            return
        if nudge_counts.get(user_id, 0) >= MAX_CONSECUTIVE_NUDGES:
            return

        response = await engine.generate_reengagement(user_id)
        # User may have come back (and cancelled us) while generating.
        if not response.messages or user_id not in manager.active:
            return

        nudge_counts[user_id] = nudge_counts.get(user_id, 0) + 1
        await _send_response_with_typing(user_id, response, mode="sexting")
        try:
            from bot.engagement import record_reengage
            await record_reengage(user_id)
        except Exception:
            pass

        # Allow one more nudge later if we're still under the cap.
        if nudge_counts.get(user_id, 0) < MAX_CONSECUTIVE_NUDGES:
            _schedule_idle_nudge(user_id)
    except asyncio.CancelledError:
        pass
    except Exception as e:
        logger.warning("Idle nudge failed for user %d: %s", user_id, e)


async def _send_response_with_typing(
    user_id: int,
    response: ChatResponse,
    mode: str,
    fixed_delay: float | None = None,
    bubble_gap: float | None = None,
):
    """Send response messages with typing simulation delays.

    fixed_delay: if set, use this fixed typing pause before EVERY bubble instead
        of the length-scaled delay (used for stories — a steady ~1s beat).
    bubble_gap: if set, use this fixed gap between bubbles instead of the random
        short gap.
    """
    import random

    ws = manager.active.get(user_id)
    if not ws:
        return

    # Nothing to say — make sure the (possibly already-running) typing indicator
    # is cleared so it doesn't get stuck on.
    if not response.messages and not response.media_offer:
        await manager.send_json(user_id, {"type": "typing_end"})
        return

    for i, msg in enumerate(response.messages):
        # typing_start is sent at the start of the first iteration, or was
        # already sent at the end of the previous iteration (immediately after
        # the last message) so the typing indicator appears with no dead gap.
        if i == 0:
            await manager.send_json(user_id, {"type": "typing_start"})

        if fixed_delay is not None:
            delay = fixed_delay
        else:
            # Typing delay scaled to message length (kept short so she feels snappy)
            length = len(msg)
            if length < 50:
                delay = random.uniform(0.5, 1.1)
            elif length < 150:
                delay = random.uniform(0.9, 1.8)
            else:
                delay = random.uniform(1.5, 2.6)

        await asyncio.sleep(delay)
        await manager.send_json(user_id, {"type": "typing_end"})

        # Send the message
        await manager.send_json(user_id, {
            "type": "message",
            "role": "assistant",
            "content": msg,
            "timestamp": time.time(),
            "mode": mode,
        })

        # Immediately start typing for the next bubble — no dead gap where the
        # user sees no activity. The optional bubble_gap sleeps WHILE typing is
        # already showing, so it just extends the typing time slightly.
        if i < len(response.messages) - 1:
            await manager.send_json(user_id, {"type": "typing_start"})
            if bubble_gap is not None and bubble_gap > 0:
                await asyncio.sleep(bubble_gap)

    # The card is a structured event after Mia's teaser bubbles. It is never a
    # text/link message, and the transport enriches only the preview derivative
    # after looking the catalog item up server-side.
    if response.media_offer:
        await manager.send_json(user_id, {"type": "typing_end"})
        try:
            offer = await _media_offer_payload(user_id, response.media_offer)
        except Exception:
            logger.exception("Could not serialize delivered media offer for user %d", user_id)
        else:
            await manager.send_json(
                user_id,
                {
                    "type": "media_offer",
                    "id": f"media-offer-{offer['offer_id']}",
                    "timestamp": time.time(),
                    "mode": mode,
                    "offer": offer,
                },
            )



# Cyrillic → Latin transliteration (Bulgarian-style), so Mia — who "only speaks
# English" — gets a name she can actually use naturally ("Нико" → "Niko").
_CYR_MAP = {
    "а": "a", "б": "b", "в": "v", "г": "g", "д": "d", "е": "e", "ж": "zh",
    "з": "z", "и": "i", "й": "y", "к": "k", "л": "l", "м": "m", "н": "n",
    "о": "o", "п": "p", "р": "r", "с": "s", "т": "t", "у": "u", "ф": "f",
    "х": "h", "ц": "ts", "ч": "ch", "ш": "sh", "щ": "sht", "ъ": "a",
    "ь": "y", "ю": "yu", "я": "ya", "ы": "y", "э": "e", "ё": "e",
}


def _latinize_name(name: str) -> str:
    out = []
    for ch in name:
        low = ch.lower()
        if low in _CYR_MAP:
            t = _CYR_MAP[low]
            out.append(t.capitalize() if ch.isupper() else t)
        else:
            out.append(ch)
    latin = "".join(out)
    # Names are data inside the system context. Keep only ordinary name
    # characters so query-string newlines or prompt-like text cannot become an
    # instruction. Collapse whitespace and enforce a small, human-sized bound.
    latin = re.sub(r"[^A-Za-z' -]", "", latin)
    latin = re.sub(r"\s+", " ", latin).strip(" '-")[:MAX_USER_NAME_CHARS]
    return capitalize_user_name(latin)


async def _message_is_blocked(user_id: int, text: str, mode: str) -> bool:
    """Apply the same input gate to normal messages and card requests."""
    if len(text) > MAX_USER_MESSAGE_CHARS:
        logger.warning("Oversized message blocked for user %d (%d chars)", user_id, len(text))
        await manager.send_json(
            user_id, {"type": "flagged", "mode": mode, "category": "too-long"}
        )
        return True
    from bot.moderation import moderate

    mod_result = await moderate(text, moderation_provider)
    if not mod_result.flagged:
        return False
    logger.warning(
        "Message flagged [%s] for user %d: %s",
        mod_result.category, user_id, text[:80],
    )
    await manager.send_json(user_id, {"type": "typing_end"})
    await manager.send_json(
        user_id,
        {"type": "flagged", "mode": mode, "category": mod_result.category},
    )
    return True


async def _record_card_user_turn(user_id: int, text: str) -> None:
    """Count one card click as one real processed user turn.

    Fantasy/story requests bypass the normal debounce engine, but they still
    produce a Mia response and therefore advance both the raw lifetime counter
    and the batch-level ``total_messages`` used by commerce pacing exactly once.
    They intentionally do not run the commerce planner on the card turn itself.
    """
    from bot.engagement import record_user_message, track_message
    from bot.router import classify_fast

    await record_user_message(user_id)
    await track_message(user_id, classify_fast(text) or "sfw")


async def _maybe_send_opening(user_id: int) -> None:
    """Mia's one-time opening — fired when the CLIENT says it's ready (the
    'start' event, sent after the intro popup is dismissed), not on raw
    connect, so her first messages land while the user is actually looking.

    Guarded by BOTH existing history (persists across restarts) and an
    in-memory in-progress set (covers concurrent reconnects / StrictMode
    double-mount), so a reload/reconnect never regenerates a fresh opening."""
    if not engine or user_id in _openings_started:
        return
    existing = await get_all_messages(user_id, mode="sexting")
    if existing:
        return
    _openings_started.add(user_id)
    # Tell the client an opening is in progress so it can lock the input
    # for its whole duration (generation + streamed bubbles). opening_end
    # is in a finally so the input can never get stuck disabled.
    await manager.send_json(user_id, {"type": "opening_start"})
    try:
        await manager.send_json(user_id, {"type": "typing_start"})
        try:
            opening = await _generate_dynamic_opening(engine)
        except Exception:
            logger.warning("Dynamic opening failed, falling back to static", exc_info=True)
            opening = engine.persona.get_random_opening()
        from bot.memory.facts import get_user_name
        opening = capitalize_names(opening, (await get_user_name(user_id),))
        parts = engine._split_response(opening)[: engine.MAX_BUBBLES]
        from bot.memory.stm import add_message as stm_add
        for part in parts:
            await stm_add(user_id, "assistant", part, mode="sexting")
        response = ChatResponse(messages=parts)
        await _send_response_with_typing(user_id, response, mode="sexting")
    finally:
        await manager.send_json(user_id, {"type": "opening_end"})
    _schedule_idle_nudge(user_id)


@app.websocket("/ws/chat")
async def websocket_chat(ws: WebSocket, user_id: int = Query(default=None), user_name: str = Query(default=None)):
    user_id = user_id or DEFAULT_USER_ID
    await manager.connect(user_id, ws)

    # Save user name as a fact (so Mia knows who she's talking to). Cyrillic
    # names are transliterated so she can use them in English text.
    if user_name:
        from bot.memory.facts import upsert_fact
        safe_name = _latinize_name(user_name)
        if safe_name:
            await upsert_fact(user_id, "name", safe_name)

    try:
        while True:
            raw = await ws.receive_text()
            data = json.loads(raw)

            msg_type = data.get("type", "message")
            mode = data.get("mode", "sexting")
            text = data.get("content", "").strip()

            # Client is ready for the one-time opening (intro popup dismissed,
            # or no popup was needed). Idempotent — see _maybe_send_opening.
            if msg_type == "start":
                await _maybe_send_opening(user_id)
                continue

            # Card request (Hear a fantasy / Hear a story): pull from the library.
            if msg_type == "card":
                kind = data.get("kind", "")
                if kind not in ("fantasy", "story"):
                    continue
                if text and await _message_is_blocked(user_id, text, mode):
                    continue
                _cancel_idle(user_id)
                nudge_counts[user_id] = 0
                logger.info("WS card from user %d: %s", user_id, kind)
                if text:
                    from bot.memory.stm import add_message as stm_add
                    await stm_add(user_id, "user", text, mode="sexting")
                await _record_card_user_turn(user_id, text)
                await manager.send_json(user_id, {"type": "card_start"})
                await manager.send_json(user_id, {"type": "typing_start"})
                response = await engine.generate_card(user_id, kind)
                # Stories and fantasies: slow delivery — 2-3s typing before each
                # bubble and 2-3s between bubbles, so it reads like she's typing
                # each part fresh (not dumping a wall of text).
                await _send_response_with_typing(
                    user_id, response, mode="sexting",
                    fixed_delay=2.5, bubble_gap=0.0,
                )
                await manager.send_json(user_id, {"type": "card_end"})
                _schedule_idle_nudge(user_id)
                continue

            if not text:
                continue

            # Normal messages and card text share one fail-closed input gate.
            if await _message_is_blocked(user_id, text, mode):
                continue

            # User is active again — cancel any pending idle nudge and reset
            # the consecutive-nudge counter so she can nudge again later.
            _cancel_idle(user_id)
            nudge_counts[user_id] = 0

            logger.info("WS message from user %d [%s]: %s", user_id, mode, text[:80])

            # Sexting mode: batched processing. Start the typing indicator
            # right away so she looks like she's already typing while the
            # debounce window collects his messages.
            await manager.send_json(user_id, {"type": "typing_start"})

            async def on_response(resp: ChatResponse):
                await _send_response_with_typing(user_id, resp, mode="sexting")
                # Start the idle countdown once she's done replying.
                _schedule_idle_nudge(user_id)

            await engine.process_sexting_batched(user_id, text, on_response=on_response)

    except WebSocketDisconnect:
        _cancel_idle(user_id)
        nudge_counts.pop(user_id, None)
        manager.disconnect(user_id, ws)
    except Exception as e:
        logger.error("WebSocket error: %s", e, exc_info=True)
        _cancel_idle(user_id)
        nudge_counts.pop(user_id, None)
        manager.disconnect(user_id, ws)


# ------------------------------------------------------------------
# Run
# ------------------------------------------------------------------

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("server.app:app", host=SERVER_HOST, port=SERVER_PORT, reload=True)
