"""
FastAPI server — entrypoint for the AI girlfriend chat demo.
Replaces the Telegram bot with HTTP + WebSocket endpoints.
"""

import asyncio
import json
import logging
import time
import base64
from contextlib import asynccontextmanager

from fastapi import FastAPI, WebSocket, WebSocketDisconnect, Query
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from fastapi.staticfiles import StaticFiles

from bot.config import (
    SERVER_HOST, SERVER_PORT, UPLOADS_DIR,
    DEFAULT_USER_ID, PERSONA_FILE_SEXTING, GEMINI_FALLBACK_MODEL,
)
from bot.memory.db import init_db, get_connection
from bot.memory.stm import get_all_messages
from bot.persona import load_persona
from bot.providers.gemini_provider import GeminiProvider
from bot.providers.grok_provider import GrokProvider
from bot.chat_engine import ChatEngine, ChatResponse

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger(__name__)

# Global chat engine
engine: ChatEngine | None = None
moderation_provider = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Initialize DB and providers on startup."""
    global engine, moderation_provider

    logger.info("Initializing database...")
    await init_db()

    logger.info("Loading persona...")
    persona = load_persona(PERSONA_FILE_SEXTING)
    nsfw_persona = persona  # one always-open persona drives everything
    logger.info("Persona loaded: %s", persona.name)

    logger.info("Initializing LLM providers...")
    # Mia is always-open, so every reply is generated by Grok (nsfw_provider).
    nsfw_provider = GrokProvider()
    classifier_provider = GeminiProvider()
    # thinking_budget=0 → no "thinking" latency; this provider only writes short
    # replies (suggestions + Grok fallback), so speed matters more than reasoning.
    fallback_provider = GeminiProvider(GEMINI_FALLBACK_MODEL, thinking_budget=0)
    vision_provider = GrokProvider()
    # Input moderation: Grok, not Gemini. Gemini's non-configurable
    # PROHIBITED_CONTENT filter refuses to even classify the very content we
    # need to detect (bestiality, CSAM, etc.), returning an empty response.
    # Grok reliably classifies it and still distinguishes adult roleplay.
    moderation_provider = GrokProvider()

    engine = ChatEngine(
        persona=persona,
        nsfw_persona=nsfw_persona,
        nsfw_provider=nsfw_provider,
        classifier_provider=classifier_provider,
        vision_provider=vision_provider,
        fallback_provider=fallback_provider,
    )
    logger.info("Chat engine ready")

    yield

    logger.info("Shutting down")


app = FastAPI(title="AI Girlfriend Chat", lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Serve user-uploaded photos (created on first upload; ensure it exists so the
# mount succeeds even before the first photo is sent).
UPLOADS_DIR.mkdir(parents=True, exist_ok=True)
app.mount("/uploads", StaticFiles(directory=str(UPLOADS_DIR)), name="uploads")


# ------------------------------------------------------------------
# REST endpoints
# ------------------------------------------------------------------

# NOTE: The sidebar profile (name, tagline, bio, "about me" grid) is curated
# directly in the frontend (frontend/app/page.tsx -> PROFILE). There is no
# /api/profile endpoint: the persona YAML doesn't carry that presentational copy,
# so the frontend is the single source of truth for profile display.


async def _generate_dynamic_opening(engine: ChatEngine) -> str:
    """Ask the LLM to write Mia's opening message — fresh every time.

    Includes the same time-of-day / location context that build_prompt injects
    into every reply, so the opening is consistent with where she'll say she is
    once he answers. Without it the bare persona defaults to a generic vibe
    that then contradicts the first time-aware reply.
    """
    from bot.time_context import get_time_prompt
    persona_prompt = engine.persona.to_system_prompt()
    time_prompt = await get_time_prompt()
    messages = [
        {
            "role": "system",
            "content": (
                f"{persona_prompt}\n\n"
                f"{time_prompt}\n\n"
                "You are starting a conversation with him for the first time. "
                "Write your opening message — the thing you finally worked up "
                "the nerve to say after wanting to since Tyler's birthday party. "
                "Ground it in where you actually are and the time of day RIGHT NOW (above) — never "
                "reference a different place or time. 2-3 short texts maximum, "
                "each on its own line. No period at the end. Be natural, be real, "
                "be yourself — crude, shameless, flirty. Do NOT use the same phrasing as your "
                "opening_lines — say something fresh."
            ),
        },
        {"role": "user", "content": "(he hasn't said anything yet — you're texting first)"},
    ]
    return await engine.nsfw_provider.generate(messages)


@app.get("/api/history/{mode}")
async def get_history(mode: str, user_id: int = Query(default=None)):
    """Return chat history for a specific mode. Opening message is sent via WebSocket."""
    user_id = user_id or DEFAULT_USER_ID
    if mode != "sexting":
        return JSONResponse({"error": "Invalid mode"}, status_code=400)

    messages = await get_all_messages(user_id, mode=mode)

    out = []
    for m in messages:
        if m["role"] not in ("user", "assistant"):
            continue
        img = m.get("image_url")
        entry = {
            "role": m["role"],
            "content": m["content"],
            "timestamp": m["timestamp"],
            "image_url": img,
        }
        out.append(entry)

    return {"mode": mode, "messages": out}


@app.post("/api/suggest")
async def suggest_reply(user_id: int = Query(default=None), mode: str = Query(default="sexting")):
    """AI Help — generate a suggested reply for the user to send to Mia."""
    if not engine:
        return JSONResponse({"error": "Engine not ready"}, status_code=503)
    uid = user_id or DEFAULT_USER_ID
    try:
        suggestion = await engine.suggest_reply(uid, mode=mode)
    except Exception as e:
        logger.warning("Suggest endpoint failed: %s", e)
        suggestion = ""
    return {"suggestion": suggestion}


@app.post("/api/reset")
async def reset_user(user_id: int = Query(default=None)):
    """Wipe all data for a user — messages, memories, facts, engagement."""
    uid = user_id or DEFAULT_USER_ID
    conn = await get_connection()
    try:
        for table in ("messages", "memories", "user_facts", "sent_content",
                      "shared_content", "engagement_state"):
            try:
                await conn.execute(f"DELETE FROM {table} WHERE user_id = ?", (uid,))
            except Exception:
                logger.debug("Reset skipped table %s (may not exist yet)", table, exc_info=True)
        await conn.commit()
        logger.info("Reset all data for user %d", uid)
    finally:
        await conn.close()

    # Clear in-memory per-user state too — otherwise a stuck/old batch task, a
    # held processing lock, or stale counters survive the reset and can block
    # the fresh conversation (the "no reply after reset" bug).
    _cancel_idle(uid)
    nudge_counts.pop(uid, None)
    _openings_started.discard(uid)
    if engine:
        engine.clear_user_state(uid)
    from bot.memory.ltm import clear_retrieval_state
    clear_retrieval_state(uid)

    return {"status": "ok", "user_id": uid}


# ------------------------------------------------------------------
# WebSocket chat
# ------------------------------------------------------------------

class ConnectionManager:
    """Track active WebSocket connections."""

    def __init__(self):
        self.active: dict[int, WebSocket] = {}

    async def connect(self, user_id: int, ws: WebSocket):
        await ws.accept()
        self.active[user_id] = ws
        logger.info("WebSocket connected: user %d", user_id)

    def disconnect(self, user_id: int):
        self.active.pop(user_id, None)
        logger.info("WebSocket disconnected: user %d", user_id)

    async def send_json(self, user_id: int, data: dict):
        ws = self.active.get(user_id)
        if ws:
            await ws.send_json(data)


manager = ConnectionManager()


# ------------------------------------------------------------------
# Online-only re-engagement ("double-text" when the user goes quiet
# while still connected). No offline queue, no cron for absent users.
# ------------------------------------------------------------------

IDLE_NUDGE_MIN_SECONDS = 120   # wait 2–4 min before a spontaneous follow-up
IDLE_NUDGE_MAX_SECONDS = 240
MAX_CONSECUTIVE_NUDGES = 1      # at most one nudge, then stay quiet until he writes

idle_tasks: dict[int, asyncio.Task] = {}
nudge_counts: dict[int, int] = {}
# Users whose one-time opening has already been started this process. Guards
# against concurrent reconnects (reload / StrictMode double-mount) regenerating
# the opening before the first assistant row is persisted.
_openings_started: set[int] = set()


def _cancel_idle(user_id: int):
    """Cancel any pending idle-nudge task for a user."""
    task = idle_tasks.pop(user_id, None)
    if task and not task.done():
        task.cancel()


def _schedule_idle_nudge(user_id: int):
    """(Re)start the idle-nudge countdown for a user."""
    _cancel_idle(user_id)
    idle_tasks[user_id] = asyncio.create_task(_idle_nudge_worker(user_id))


async def _idle_nudge_worker(user_id: int):
    """After a quiet gap (still online), send a spontaneous follow-up."""
    import random
    try:
        await asyncio.sleep(random.uniform(IDLE_NUDGE_MIN_SECONDS, IDLE_NUDGE_MAX_SECONDS))

        if user_id not in manager.active or not engine:
            return
        if nudge_counts.get(user_id, 0) >= MAX_CONSECUTIVE_NUDGES:
            return

        response = await engine.generate_reengagement(user_id)
        # User may have come back (and cancelled us) while generating.
        if not response.messages or user_id not in manager.active:
            return

        nudge_counts[user_id] = nudge_counts.get(user_id, 0) + 1
        await _send_response_with_typing(user_id, response, mode="sexting")
        try:
            from bot.engagement import record_reengage
            await record_reengage(user_id)
        except Exception:
            pass

        # Allow one more nudge later if we're still under the cap.
        if nudge_counts.get(user_id, 0) < MAX_CONSECUTIVE_NUDGES:
            _schedule_idle_nudge(user_id)
    except asyncio.CancelledError:
        pass
    except Exception as e:
        logger.warning("Idle nudge failed for user %d: %s", user_id, e)


async def _send_response_with_typing(
    user_id: int,
    response: ChatResponse,
    mode: str,
    fixed_delay: float | None = None,
    bubble_gap: float | None = None,
):
    """Send response messages with typing simulation delays.

    fixed_delay: if set, use this fixed typing pause before EVERY bubble instead
        of the length-scaled delay (used for stories — a steady ~1s beat).
    bubble_gap: if set, use this fixed gap between bubbles instead of the random
        short gap.
    """
    import random

    ws = manager.active.get(user_id)
    if not ws:
        return

    # Nothing to say — make sure the (possibly already-running) typing indicator
    # is cleared so it doesn't get stuck on.
    if not response.messages:
        await manager.send_json(user_id, {"type": "typing_end"})
        return

    for i, msg in enumerate(response.messages):
        # typing_start is sent at the start of the first iteration, or was
        # already sent at the end of the previous iteration (immediately after
        # the last message) so the typing indicator appears with no dead gap.
        if i == 0:
            await manager.send_json(user_id, {"type": "typing_start"})

        if fixed_delay is not None:
            delay = fixed_delay
        else:
            # Typing delay scaled to message length (kept short so she feels snappy)
            length = len(msg)
            if length < 50:
                delay = random.uniform(0.5, 1.1)
            elif length < 150:
                delay = random.uniform(0.9, 1.8)
            else:
                delay = random.uniform(1.5, 2.6)

        await asyncio.sleep(delay)
        await manager.send_json(user_id, {"type": "typing_end"})

        # Send the message
        await manager.send_json(user_id, {
            "type": "message",
            "role": "assistant",
            "content": msg,
            "timestamp": time.time(),
            "mode": mode,
        })

        # Immediately start typing for the next bubble — no dead gap where the
        # user sees no activity. The optional bubble_gap sleeps WHILE typing is
        # already showing, so it just extends the typing time slightly.
        if i < len(response.messages) - 1:
            await manager.send_json(user_id, {"type": "typing_start"})
            if bubble_gap is not None and bubble_gap > 0:
                await asyncio.sleep(bubble_gap)



@app.websocket("/ws/chat")
async def websocket_chat(ws: WebSocket, user_id: int = Query(default=None), user_name: str = Query(default=None)):
    user_id = user_id or DEFAULT_USER_ID
    await manager.connect(user_id, ws)

    # Save user name as a fact (so Mia knows who she's talking to)
    if user_name:
        from bot.memory.facts import upsert_fact
        await upsert_fact(user_id, "name", user_name)

    # New user — Mia initiates with a dynamically generated opening, ONCE.
    # Guard on BOTH existing history (persists across restarts) and an in-memory
    # in-progress set (covers concurrent reconnects / StrictMode double-mount),
    # so a reload/reconnect never regenerates a fresh opening. The old guard used
    # count_turns() — which counts only USER messages — so it stayed 0 until the
    # user replied and re-fired an opening on every reconnect.
    if engine and user_id not in _openings_started:
        existing = await get_all_messages(user_id, mode="sexting")
        if not existing:
            _openings_started.add(user_id)
            # Tell the client an opening is in progress so it can lock the input
            # for its whole duration (generation + streamed bubbles). opening_end
            # is in a finally so the input can never get stuck disabled.
            await manager.send_json(user_id, {"type": "opening_start"})
            try:
                await manager.send_json(user_id, {"type": "typing_start"})
                try:
                    opening = await _generate_dynamic_opening(engine)
                except Exception:
                    logger.warning("Dynamic opening failed, falling back to static", exc_info=True)
                    opening = engine.persona.get_random_opening()
                parts = [p.strip() for p in opening.split("\n") if p.strip()]
                from bot.memory.stm import add_message as stm_add
                for part in parts:
                    await stm_add(user_id, "assistant", part, mode="sexting")
                response = ChatResponse(messages=parts)
                await _send_response_with_typing(user_id, response, mode="sexting")
            finally:
                await manager.send_json(user_id, {"type": "opening_end"})
            _schedule_idle_nudge(user_id)

    try:
        while True:
            raw = await ws.receive_text()
            data = json.loads(raw)

            msg_type = data.get("type", "message")
            mode = data.get("mode", "sexting")
            text = data.get("content", "").strip()

            # Card request (Hear a fantasy / Hear a story): pull from the library.
            if msg_type == "card":
                kind = data.get("kind", "")
                if kind not in ("fantasy", "story"):
                    continue
                _cancel_idle(user_id)
                nudge_counts[user_id] = 0
                logger.info("WS card from user %d: %s", user_id, kind)
                if text:
                    from bot.memory.stm import add_message as stm_add
                    await stm_add(user_id, "user", text, mode="sexting")
                await manager.send_json(user_id, {"type": "card_start"})
                await manager.send_json(user_id, {"type": "typing_start"})
                response = await engine.generate_card(user_id, kind)
                # Stories and fantasies: slow delivery — 2-3s typing before each
                # bubble and 2-3s between bubbles, so it reads like she's typing
                # each part fresh (not dumping a wall of text).
                await _send_response_with_typing(
                    user_id, response, mode="sexting",
                    fixed_delay=2.5, bubble_gap=0.0,
                )
                await manager.send_json(user_id, {"type": "card_end"})
                _schedule_idle_nudge(user_id)
                continue

            # Handle image uploads via WebSocket (base64)
            image_bytes = None
            if data.get("image"):
                try:
                    image_bytes = base64.b64decode(data["image"])
                except Exception:
                    logger.warning("Failed to decode uploaded image for user %d", user_id, exc_info=True)

            if not text and not image_bytes:
                continue

            # Input moderation gate — runs BEFORE the engine. Blocks prohibited
            # content (underage, bestiality, non-consent) with a system bubble
            # instead of letting it reach the LLM and getting a silent refusal.
            if text:
                from bot.moderation import moderate
                mod_result = await moderate(text, moderation_provider)
                if mod_result.flagged:
                    logger.warning(
                        "Message flagged [%s] for user %d: %s",
                        mod_result.category, user_id, text[:80],
                    )
                    await manager.send_json(user_id, {"type": "typing_end"})
                    await manager.send_json(user_id, {"type": "flagged", "mode": mode})
                    continue

            # User is active again — cancel any pending idle nudge and reset
            # the consecutive-nudge counter so she can nudge again later.
            _cancel_idle(user_id)
            nudge_counts[user_id] = 0

            logger.info("WS message from user %d [%s]: %s", user_id, mode, (text or "[image]")[:80])

            # Sexting mode: batched processing. Start the typing indicator
            # right away so she looks like she's already typing while the
            # debounce window collects his messages.
            await manager.send_json(user_id, {"type": "typing_start"})

            async def on_response(resp: ChatResponse):
                await _send_response_with_typing(user_id, resp, mode="sexting")
                # Start the idle countdown once she's done replying.
                _schedule_idle_nudge(user_id)

            await engine.process_sexting_batched(
                user_id, text, image_bytes=image_bytes, on_response=on_response
            )

    except WebSocketDisconnect:
        _cancel_idle(user_id)
        nudge_counts.pop(user_id, None)
        manager.disconnect(user_id)
    except Exception as e:
        logger.error("WebSocket error: %s", e, exc_info=True)
        _cancel_idle(user_id)
        nudge_counts.pop(user_id, None)
        manager.disconnect(user_id)


# ------------------------------------------------------------------
# Run
# ------------------------------------------------------------------

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("server.app:app", host=SERVER_HOST, port=SERVER_PORT, reload=True)
